
package com.monsanto.irdsoapservices.retailseller.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RetailSellerInformationService", targetNamespace = "urn:monsanto:services:wsdl:salesorder:1:0", wsdlLocation = "http://services-dint.monsanto.com/ECOM_SalesDoc/ProxyServices/RetailSellerInformation?wsdl")
public class RetailSellerInformationService_Service
    extends Service
{

    private final static URL RETAILSELLERINFORMATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.monsanto.irdsoapservices.retailseller.schema.RetailSellerInformationService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.monsanto.irdsoapservices.retailseller.schema.RetailSellerInformationService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://services-dint.monsanto.com/ECOM_SalesDoc/RetailSellerInformation?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://services-dint.monsanto.com/ECOM_SalesDoc/ProxyServices/RetailSellerInformation?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RETAILSELLERINFORMATIONSERVICE_WSDL_LOCATION = url;
    }

    public RetailSellerInformationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RetailSellerInformationService_Service() {
        super(RETAILSELLERINFORMATIONSERVICE_WSDL_LOCATION, new QName("urn:monsanto:services:wsdl:salesorder:1:0", "RetailSellerInformationService"));
    }

    /**
     * 
     * @return
     *     returns RetailSellerInformationService
     */
    @WebEndpoint(name = "RetailSellerInformationServicePort")
    public RetailSellerInformationService getRetailSellerInformationServicePort() {
        return super.getPort(new QName("urn:monsanto:services:wsdl:salesorder:1:0", "RetailSellerInformationServicePort"), RetailSellerInformationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RetailSellerInformationService
     */
    @WebEndpoint(name = "RetailSellerInformationServicePort")
    public RetailSellerInformationService getRetailSellerInformationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:monsanto:services:wsdl:salesorder:1:0", "RetailSellerInformationServicePort"), RetailSellerInformationService.class, features);
    }

}
