
package com.monsanto.irdsoapservices.retailseller.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RetailSellerInformationService", targetNamespace = "urn:monsanto:services:wsdl:salesorder:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RetailSellerInformationService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.retailseller.schema.RetailSellerResponseType
     * @throws RetailSellerFault
     */
    @WebMethod
    @WebResult(name = "RetailSellerResponse", targetNamespace = "urn:ecms:schema:retailsellerinformation:request:1:0", partName = "retailSellerResponse")
    public RetailSellerResponseType saveRetailSellerInformation(
        @WebParam(name = "RetailSellerInformation", targetNamespace = "urn:ecms:schema:retailsellerinformation:request:1:0", partName = "request")
        RetailSellerInformationType request)
        throws RetailSellerFault
    ;

}
