
package com.monsanto.irdsoapservices.salesorder.schema;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.monsanto.irdsoapservices.datasummary.schema.DataSummaryReport;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SalesOrderService", targetNamespace = "urn:monsanto:services:wsdl:salesorder:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.salesorder.schema.ObjectFactory.class,
    com.monsanto.irdsoapservices.datasummary.schema.ObjectFactory.class
})
public interface SalesOrderService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.salesorder.schema.SalesOrderReportResponseType
     * @throws SalesOrderFault
     */
    @WebMethod
    @WebResult(name = "SalesOrderReportResponse", targetNamespace = "urn:ecms:schema:salesorderreport:response:1:0", partName = "salesOrderReportResponse")
    public SalesOrderReportResponseType getSalesOrderReport(
        @WebParam(name = "SalesOrderReport", targetNamespace = "urn:ecms:schema:salesorderreport:response:1:0", partName = "request")
        SalesOrderReport request)
        throws SalesOrderFault
    ;

    /**
     * 
     * @param request
     */
    @WebMethod
    @Oneway
    public void getDataSummaryReport(
        @WebParam(name = "DataSummaryReport", targetNamespace = "urn:ecms:schema:datasummaryreport:response:1:0", partName = "request")
        DataSummaryReport request);

}
