
package com.monsanto.irdsoapservices.salesorder.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SalesOrderService", targetNamespace = "urn:monsanto:services:wsdl:salesorder:1:0", wsdlLocation = "http://services-dint.monsanto.com/ECOM_SalesDoc/SalesOrder?wsdl")
public class SalesOrderService_Service
    extends Service
{

    private final static URL SALESORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.monsanto.irdsoapservices.salesorder.schema.SalesOrderService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.monsanto.irdsoapservices.salesorder.schema.SalesOrderService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://services-dint.monsanto.com/ECOM_SalesDoc/SalesOrder?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://services-dint.monsanto.com/ECOM_SalesDoc/SalesOrder?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SALESORDERSERVICE_WSDL_LOCATION = url;
    }

    public SalesOrderService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesOrderService_Service() {
        super(SALESORDERSERVICE_WSDL_LOCATION, new QName("urn:monsanto:services:wsdl:salesorder:1:0", "SalesOrderService"));
    }

    /**
     * 
     * @return
     *     returns SalesOrderService
     */
    @WebEndpoint(name = "SalesOrderServicePort")
    public SalesOrderService getSalesOrderServicePort() {
        return super.getPort(new QName("urn:monsanto:services:wsdl:salesorder:1:0", "SalesOrderServicePort"), SalesOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesOrderService
     */
    @WebEndpoint(name = "SalesOrderServicePort")
    public SalesOrderService getSalesOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:monsanto:services:wsdl:salesorder:1:0", "SalesOrderServicePort"), SalesOrderService.class, features);
    }

}
