
package com.monsanto.irdsoapservices.service;

import com.monsanto.irdsoapservices.agreements.schema.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountAgreementService", targetNamespace = "urn:monsanto:ird:services:wsdl:account:agreement:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.agreements.schema.ObjectFactory.class,
    com.monsanto.isdcommon.header.schema.ObjectFactory.class
})
public interface AccountAgreementService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreements.schema.GetAgreementsResponseType
     * @throws AccountAgreementsFault
     */
    @WebMethod
    @WebResult(name = "GetAgreementsResponse", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "getAgreementsResponse")
    public GetAgreementsResponseType getAgreements(
        @WebParam(name = "GetAgreementsRequest", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "request")
        GetAgreementsRequestType request)
        throws AccountAgreementsFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreements.schema.UpdateAgreementResponseType
     * @throws AccountAgreementsFault
     */
    @WebMethod
    @WebResult(name = "UpdateAgreementResponse", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "updateAgreementResponse")
    public UpdateAgreementResponseType updateAgreement(
        @WebParam(name = "UpdateAgreementRequest", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "request")
        UpdateAgreementRequestType request)
        throws AccountAgreementsFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreements.schema.GetAgreementHierarchyResponseType
     * @throws AccountAgreementsFault
     */
    @WebMethod
    @WebResult(name = "GetAgreementHierarchyResponse", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "getAgreementHierarchyResponse")
    public GetAgreementHierarchyResponseType getAgreementHierarchy(
        @WebParam(name = "GetAgreementHierarchyRequest", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "request")
        GetAgreementHierarchyRequestType request)
        throws AccountAgreementsFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreements.schema.GetSignersForAgreementsResponseType
     * @throws AccountAgreementsFault
     */
    @WebMethod
    @WebResult(name = "GetSignersForAgreementsResponse", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "getSignersForAgreementsResponse")
    public GetSignersForAgreementsResponseType getSignersForAgreements(
        @WebParam(name = "GetSignersForAgreementsRequest", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "request")
        GetSignersForAgreementsRequestType request)
        throws AccountAgreementsFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreements.schema.GetSignersForExpiredAgreementsResponseType
     * @throws AccountAgreementsFault
     */
    @WebMethod
    @WebResult(name = "GetSignersForExpiredAgreementsResponse", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "getSignersForExpiredAgreementsResponse")
    public GetSignersForExpiredAgreementsResponseType getSignersForExpiredAgreements(
        @WebParam(name = "GetSignersForExpiredAgreementsRequest", targetNamespace = "urn:monsanto:ird:services:account:agreement", partName = "request")
        GetSignersForExpiredAgreementsRequestType request)
        throws AccountAgreementsFault
    ;

}
