
package com.monsanto.irdsoapservices.service;

import com.monsanto.irdsoapservices.schema.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccountInformationService", targetNamespace = "urn:monsanto:ird:services:wsdl:account:information:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.schema.ObjectFactory.class,
    com.monsanto.isdcommon.header.schema.ObjectFactory.class
})
public interface AccountInformationService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.GetContactsResponseType
     * @throws AccountInformationFault
     */
//    @WebMethod
//    @WebResult(name = "GetContactsResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "GetContactsResponse")
//    public GetContactsResponseType getContacts(
//        @WebParam(name = "GetContactsRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
//        GetContactsRequestType request)
//        throws AccountInformationFault
//    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.GetAccountAttributesResponseType
     * @throws AccountInformationFault
     */
    @WebMethod
    @WebResult(name = "GetAccountAttributesResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "GetAccountAttributesResponse")
    public GetAccountAttributesResponseType getAccountAttributes(
        @WebParam(name = "GetAccountAttributesRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
        GetAccountAttributesRequestType request)
        throws AccountInformationFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.SaveAccountDetailsResponseType
     * @throws AccountInformationFault
     */
    @WebMethod
    @WebResult(name = "SaveAccountDetailsResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "SaveDetailsResponse")
    public SaveAccountDetailsResponseType saveAccountDetails(
        @WebParam(name = "SaveAccountDetailsRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
        SaveAccountDetailsRequestType request)
        throws AccountInformationFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.SaveAccountAttributesResponseType
     * @throws AccountInformationFault
     */
    @WebMethod
    @WebResult(name = "SaveAccountAttributesResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "SaveAccountAttributesResponse")
    public SaveAccountAttributesResponseType saveAccountAttributes(
        @WebParam(name = "SaveAccountAttributesRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
        SaveAccountAttributesRequestType request)
        throws AccountInformationFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.GetAccountDetailsResponseType
     * @throws AccountInformationFault
     */
    @WebMethod
    @WebResult(name = "GetAccountDetailsResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "GetAccountDetailsResponse")
    public GetAccountDetailsResponseType getAccountDetails(
        @WebParam(name = "GetAccountDetailsRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
        GetAccountDetailsRequestType request)
        throws AccountInformationFault
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.SaveContactsResponseType
     * @throws AccountInformationFault
     */
//    @WebMethod
//    @WebResult(name = "SaveContactsResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "SaveContactsResponse")
//    public SaveContactsResponseType saveContacts(
//        @WebParam(name = "SaveContactsRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
//        SaveContactsRequestType request)
//        throws AccountInformationFault
//    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.schema.GetAssociatedEmployeesResponseType
     * @throws AccountInformationFault
     */
    @WebMethod
    @WebResult(name = "GetAssociatedEmployeesResponse", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "GetAssociatedEmployeesResponse")
    public GetAssociatedEmployeesResponseType getAssociatedEmployees(
        @WebParam(name = "GetAssociatedEmployeesRequest", targetNamespace = "urn:monsanto:ird:services:account:information", partName = "request")
        GetAssociatedEmployeesRequestType request)
        throws AccountInformationFault
    ;

}
