
package com.monsanto.irdsoapservices.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccountAgreementService", targetNamespace = "urn:monsanto:ird:services:wsdl:account:agreement:1:0", wsdlLocation = "http://services-dint.monsanto.com/IrdServices/AccountAgreements?wsdl")
public class AccountAgreementService_Service
    extends Service
{

    private final static URL ACCOUNTAGREEMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.monsanto.irdsoapservices.service.AccountAgreementService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.monsanto.irdsoapservices.service.AccountAgreementService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://services-dint.monsanto.com/IrdServices/AccountAgreements?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://services-dint.monsanto.com/IrdServices/AccountAgreements?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCOUNTAGREEMENTSERVICE_WSDL_LOCATION = url;
    }

    public AccountAgreementService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountAgreementService_Service() {
        super(ACCOUNTAGREEMENTSERVICE_WSDL_LOCATION, new QName("urn:monsanto:ird:services:wsdl:account:agreement:1:0", "AccountAgreementService"));
    }

    /**
     * 
     * @return
     *     returns AccountAgreementService
     */
    @WebEndpoint(name = "AccountAgreementServicePort")
    public AccountAgreementService getAccountAgreementServicePort() {
        return super.getPort(new QName("urn:monsanto:ird:services:wsdl:account:agreement:1:0", "AccountAgreementServicePort"), AccountAgreementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountAgreementService
     */
    @WebEndpoint(name = "AccountAgreementServicePort")
    public AccountAgreementService getAccountAgreementServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:monsanto:ird:services:wsdl:account:agreement:1:0", "AccountAgreementServicePort"), AccountAgreementService.class, features);
    }

}
