
package com.monsanto.irdsoapservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.monsanto.irdsoapservices.brands.schema.GetBrandsRequestType;
import com.monsanto.irdsoapservices.brands.schema.GetBrandsResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BrandsService", targetNamespace = "urn:monsanto:ird:services:wsdl:brands:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.isdcommon.header.schema.ObjectFactory.class,
    com.monsanto.irdsoapservices.brands.schema.ObjectFactory.class
})
public interface BrandsService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.brands.schema.GetBrandsResponseType
     * @throws BrandsFault
     */
    @WebMethod
    @WebResult(name = "GetBrandsResponse", targetNamespace = "urn:monsanto:ird:services:brands", partName = "getBrandsResponse")
    public GetBrandsResponseType getBrands(
        @WebParam(name = "GetBrandsRequest", targetNamespace = "urn:monsanto:ird:services:brands", partName = "request")
        GetBrandsRequestType request)
        throws BrandsFault
    ;

}
