
package com.monsanto.irdsoapservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.monsanto.irdsoapservices.contacts.schema.AddContactFunctionRequestType;
import com.monsanto.irdsoapservices.contacts.schema.AddContactFunctionResponseType;
import com.monsanto.irdsoapservices.contacts.schema.DeleteContactRequestType;
import com.monsanto.irdsoapservices.contacts.schema.DeleteContactResponseType;
import com.monsanto.irdsoapservices.contacts.schema.GetContactsRequestType;
import com.monsanto.irdsoapservices.contacts.schema.GetContactsResponseType;
import com.monsanto.irdsoapservices.contacts.schema.InsertContactRequestType;
import com.monsanto.irdsoapservices.contacts.schema.InsertContactResponseType;
import com.monsanto.irdsoapservices.contacts.schema.RemoveContactFunctionRequestType;
import com.monsanto.irdsoapservices.contacts.schema.RemoveContactFunctionResponseType;
import com.monsanto.irdsoapservices.contacts.schema.UpdateContactsRequestType;
import com.monsanto.irdsoapservices.contacts.schema.UpdateContactsResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContactService", targetNamespace = "urn:monsanto:ird:services:wsdl:contacts:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.contacts.schema.ObjectFactory.class,
    com.monsanto.isdcommon.header.schema.ObjectFactory.class
})
public interface ContactService {


    /**
     * 
     * @param getContactsRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.GetContactsResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "GetContactsResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "getContactsResponse")
    public GetContactsResponseType getContacts(
        @WebParam(name = "GetContactsRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "getContactsRequest")
        GetContactsRequestType getContactsRequest)
        throws ContactsFault
    ;

    /**
     * 
     * @param insertContactsRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.InsertContactResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "InsertContactResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "insertContactsResponse")
    public InsertContactResponseType insertContacts(
        @WebParam(name = "InsertContactRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "insertContactsRequest")
        InsertContactRequestType insertContactsRequest)
        throws ContactsFault
    ;

    /**
     * 
     * @param updateContactsRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.UpdateContactsResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "UpdateContactsResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "updateContactsResponse")
    public UpdateContactsResponseType updateContacts(
        @WebParam(name = "UpdateContactsRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "updateContactsRequest")
        UpdateContactsRequestType updateContactsRequest)
        throws ContactsFault
    ;

    /**
     * 
     * @param deleteContactRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.DeleteContactResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "DeleteContactResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "deleteContactResponse")
    public DeleteContactResponseType deleteContact(
        @WebParam(name = "DeleteContactRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "deleteContactRequest")
        DeleteContactRequestType deleteContactRequest)
        throws ContactsFault
    ;

    /**
     * 
     * @param addContactFunctionRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.AddContactFunctionResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "AddContactFunctionResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "addContactFunctionResponse")
    public AddContactFunctionResponseType addContactFunction(
        @WebParam(name = "AddContactFunctionRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "addContactFunctionRequest")
        AddContactFunctionRequestType addContactFunctionRequest)
        throws ContactsFault
    ;

    /**
     * 
     * @param removeContactFunctionRequest
     * @return
     *     returns com.monsanto.irdsoapservices.contacts.schema.RemoveContactFunctionResponseType
     * @throws ContactsFault
     */
    @WebMethod
    @WebResult(name = "RemoveContactFunctionResponse", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "removeContactFunctionResponse")
    public RemoveContactFunctionResponseType removeContactFunction(
        @WebParam(name = "RemoveContactFunctionRequest", targetNamespace = "urn:monsanto:ird:services:contacts", partName = "removeContactFunctionRequest")
        RemoveContactFunctionRequestType removeContactFunctionRequest)
        throws ContactsFault
    ;

}
