
package com.monsanto.irdsoapservices.service;

import javax.xml.ws.WebFault;
import com.monsanto.irdsoapservices.contacts.schema.ExceptionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ContactsFault", targetNamespace = "urn:monsanto:ird:services:contacts")
public class ContactsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ContactsFault(String message, ExceptionType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ContactsFault(String message, ExceptionType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.monsanto.irdsoapservices.contacts.schema.ExceptionType
     */
    public ExceptionType getFaultInfo() {
        return faultInfo;
    }

}
