
package com.monsanto.irdsoapservices.service;

import javax.xml.ws.WebFault;
import com.monsanto.irdsoapservices.vistiveprocessorlist.schema.VistiveProcessorListFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "VistiveProcessorListFault", targetNamespace = "urn:ecms:schema:vistiveprocessorlist:1:0")
public class VistiveProcessorListFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private VistiveProcessorListFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public VistiveProcessorListFault(String message, VistiveProcessorListFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public VistiveProcessorListFault(String message, VistiveProcessorListFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.monsanto.irdsoapservices.vistiveprocessorlist.schema.VistiveProcessorListFaultType
     */
    public VistiveProcessorListFaultType getFaultInfo() {
        return faultInfo;
    }

}
