
package com.monsanto.irdsoapservices.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.monsanto.irdsoapservices.vistiveprocessorlist.schema.VistiveProcessorListRequestType;
import com.monsanto.irdsoapservices.vistiveprocessorlist.schema.VistiveProcessorListType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "VistiveProcessorListService", targetNamespace = "urn:monsanto:ird:services:wsdl:vistiveprocessorlist:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.vistiveprocessorlist.schema.ObjectFactory.class,
    com.monsanto.cidx.header.schema.ObjectFactory.class
})
public interface VistiveProcessorListService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.vistiveprocessorlist.schema.VistiveProcessorListType
     * @throws VistiveProcessorListFault
     */
    @WebMethod
    @WebResult(name = "VistiveProcessorList", targetNamespace = "urn:ecms:schema:vistiveprocessorlist:1:0", partName = "getVistiveProcessorResponse")
    public VistiveProcessorListType getVistiveProcessorList(
        @WebParam(name = "VistiveProcessorListRequest", targetNamespace = "urn:ecms:schema:vistiveprocessorlist:1:0", partName = "request")
        VistiveProcessorListRequestType request)
        throws VistiveProcessorListFault
    ;

}
