
package com.monsanto.irdsoapservices.agreementstatuspartners.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AgreementStatusService", targetNamespace = "urn:monsanto:services:wsdl:agreementstatus:1:1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgreementStatusService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreementstatuspartners.schema.AgreementStatusResponseType
     * @throws AgreementStatusFault
     */
    @WebMethod
    @WebResult(name = "AgreementStatusResponse", targetNamespace = "urn:cidx:names:specification:ces:schema:all:5:3", partName = "agreementStatusResponse")
    public AgreementStatusResponseType getAgreementStatus(
        @WebParam(name = "AgreementStatusRequest", targetNamespace = "urn:cidx:names:specification:ces:schema:all:5:3", partName = "request")
        AgreementStatusRequestType request)
        throws AgreementStatusFault
    ;

}
