
package com.monsanto.irdsoapservices.agreementstatus.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.monsanto.irdsoapservices.agreementstatus.schema.request.AgreementStatusRequest;
import com.monsanto.irdsoapservices.agreementstatus.schema.response.AgreementStatusResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AgreementStatusService", targetNamespace = "urn:monsanto:services:wsdl:agreementstatus:1:0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.monsanto.irdsoapservices.agreementstatus.schema.response.ObjectFactory.class,
    com.monsanto.irdsoapservices.agreementstatus.schema.request.ObjectFactory.class
})
public interface AgreementStatusService {


    /**
     * 
     * @param request
     * @return
     *     returns com.monsanto.irdsoapservices.agreementstatus.schema.response.AgreementStatusResponseType
     * @throws AgreementStatusFault
     */
    @WebMethod
    @WebResult(name = "AgreementStatusResponse", targetNamespace = "urn:ecms:schema:agreement:response:2:0", partName = "agreementStatusResponse")
    public AgreementStatusResponseType getAgreementStatus(
        @WebParam(name = "AgreementStatusRequest", targetNamespace = "urn:ecms:schema:agreement:request:2:0", partName = "request")
        AgreementStatusRequest request)
        throws AgreementStatusFault
    ;

}
