
package com.monsanto.irdsoapservices.agreementstatus.schema;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AgreementStatusService", targetNamespace = "urn:monsanto:services:wsdl:agreementstatus:1:0", wsdlLocation = "file:/C:/SVN-Development/IRDSoapServices/trunk/IrdServicesWeb/src/main/resources/AgreementStatus_2-0.wsdl")
public class AgreementStatusService_Service
    extends Service
{

    private final static URL AGREEMENTSTATUSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.monsanto.irdsoapservices.agreementstatus.schema.AgreementStatusService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.monsanto.irdsoapservices.agreementstatus.schema.AgreementStatusService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/SVN-Development/IRDSoapServices/trunk/IrdServicesWeb/src/main/resources/AgreementStatus_2-0.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/SVN-Development/IRDSoapServices/trunk/IrdServicesWeb/src/main/resources/AgreementStatus_2-0.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AGREEMENTSTATUSSERVICE_WSDL_LOCATION = url;
    }

    public AgreementStatusService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgreementStatusService_Service() {
        super(AGREEMENTSTATUSSERVICE_WSDL_LOCATION, new QName("urn:monsanto:services:wsdl:agreementstatus:1:0", "AgreementStatusService"));
    }

    /**
     * 
     * @return
     *     returns AgreementStatusService
     */
    @WebEndpoint(name = "AgreementStatusServicePort")
    public AgreementStatusService getAgreementStatusServicePort() {
        return super.getPort(new QName("urn:monsanto:services:wsdl:agreementstatus:1:0", "AgreementStatusServicePort"), AgreementStatusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgreementStatusService
     */
    @WebEndpoint(name = "AgreementStatusServicePort")
    public AgreementStatusService getAgreementStatusServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:monsanto:services:wsdl:agreementstatus:1:0", "AgreementStatusServicePort"), AgreementStatusService.class, features);
    }

}
